from typing import Protocol

class AIProvider(Protocol):
    def normalize_markdown(self, raw_text: str, metadata: dict) -> str: ...
    def suggest_tags(self, markdown: str, metadata: dict) -> list[str]: ...
